import {
  SEQUELIZE_CONNECTION,
  SEQUELIZE_DATABASE,
  SEQUELIZE_HOST,
  SEQUELIZE_PASSWORD,
  SEQUELIZE_PORT,
  SEQUELIZE_TIMEZONE,
  SEQUELIZE_USERNAME,
} from './env'

module.exports = {
  username: SEQUELIZE_USERNAME,
  password: SEQUELIZE_PASSWORD,
  database: SEQUELIZE_DATABASE,
  host: SEQUELIZE_HOST,
  port: SEQUELIZE_PORT,
  dialect: SEQUELIZE_CONNECTION,
  timezone: SEQUELIZE_TIMEZONE,
}
